-- Marketbook - S08.s2 - Grupo 5
-- Ejecutar en SQL Editor de un proyecto Supabase vacío (o revisar primero
-- si ya existen estas tablas: no sobrescribir un esquema preexistente).
-- Convención del avance: usuarios.id = usuarios.auth_id = auth.users.id.

create table if not exists public.usuarios (
  id uuid primary key references auth.users(id) on delete cascade,
  auth_id uuid not null unique references auth.users(id) on delete cascade,
  nombre text not null default '',
  correo text not null default '',
  foto_perfil text,
  constraint usuarios_id_auth_igual check (id = auth_id)
);

create table if not exists public.publicaciones (
  id bigint generated by default as identity primary key,
  vendedor_id uuid not null references public.usuarios(id) on delete cascade,
  titulo text not null check (length(trim(titulo)) between 1 and 120),
  autor text not null check (length(trim(autor)) between 1 and 100),
  categoria text,
  isbn text,
  estado_libro text not null default 'Bueno'
    check (estado_libro in ('Nuevo', 'Como nuevo', 'Bueno', 'Regular')),
  precio numeric(10, 2) not null check (precio > 0),
  descripcion text not null default '',
  estado_publicacion text not null default 'activa'
    check (estado_publicacion in ('activa', 'vendida', 'retirada')),
  fecha_publicacion timestamptz not null default now()
);

create index if not exists publicaciones_estado_fecha_idx
  on public.publicaciones(estado_publicacion, fecha_publicacion desc);
create index if not exists publicaciones_vendedor_idx
  on public.publicaciones(vendedor_id);

-- Crear perfil automáticamente al registrarse mediante Supabase Auth.
create or replace function public.crear_perfil_marketbook()
returns trigger
language plpgsql security definer set search_path = ''
as $$
begin
  insert into public.usuarios (id, auth_id, nombre, correo)
  values (
    new.id, new.id,
    coalesce(nullif(new.raw_user_meta_data ->> 'nombre', ''), split_part(new.email, '@', 1)),
    coalesce(new.email, '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_marketbook on auth.users;
create trigger on_auth_user_created_marketbook
  after insert on auth.users
  for each row execute procedure public.crear_perfil_marketbook();

alter table public.usuarios enable row level security;
alter table public.publicaciones enable row level security;

revoke all on table public.usuarios, public.publicaciones from anon, authenticated;
grant usage on schema public to authenticated;
grant select on table public.usuarios to authenticated;
grant select, insert, update, delete on table public.publicaciones to authenticated;
grant usage, select on sequence public.publicaciones_id_seq to authenticated;

-- Los visitantes sin iniciar sesión no tienen acceso.
drop policy if exists "marketbook_usuarios_propio_select" on public.usuarios;
create policy "marketbook_usuarios_propio_select"
  on public.usuarios for select to authenticated
  using (id = (select auth.uid()));

-- Mostrar activas a cualquier autenticado y las propias independientemente del estado.
drop policy if exists "marketbook_publicaciones_select" on public.publicaciones;
create policy "marketbook_publicaciones_select"
  on public.publicaciones for select to authenticated
  using (estado_publicacion = 'activa' or vendedor_id = (select auth.uid()));

-- Solo publicar a nombre de la sesión que realizó el POST.
drop policy if exists "marketbook_publicaciones_insert" on public.publicaciones;
create policy "marketbook_publicaciones_insert"
  on public.publicaciones for insert to authenticated
  with check (
    vendedor_id = (select auth.uid())
    and estado_publicacion = 'activa'
  );

-- Solo modificar las publicaciones propias, sin transferir su propiedad.
drop policy if exists "marketbook_publicaciones_update" on public.publicaciones;
create policy "marketbook_publicaciones_update"
  on public.publicaciones for update to authenticated
  using (vendedor_id = (select auth.uid()))
  with check (vendedor_id = (select auth.uid()));

-- DELETE físico solo para el propietario (demostración puntual del método REST).
drop policy if exists "marketbook_publicaciones_delete" on public.publicaciones;
create policy "marketbook_publicaciones_delete"
  on public.publicaciones for delete to authenticated
  using (vendedor_id = (select auth.uid()));
