-- ============================================================================
-- Marketbook - Avance 2 - Grupo 5
-- COMPRA Y VENTA + PERFIL + REGLAS DE SEGURIDAD
--
-- Requisito: haber ejecutado antes 20260928_s08_publicaciones.sql
-- Se puede ejecutar más de una vez sin romper nada (idempotente).
-- Ejecutar completo en Supabase > SQL Editor > New query > Run.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. USUARIOS: el nombre es visible para otros usuarios (vendedor/comprador),
--    el correo NO. Cada quien puede editar solo su nombre y foto.
-- ----------------------------------------------------------------------------
create or replace function public.crear_perfil_marketbook()
returns trigger
language plpgsql security definer set search_path = ''
as $$
begin
  insert into public.usuarios (id, auth_id, nombre, correo)
  values (
    new.id, new.id,
    left(trim(coalesce(nullif(new.raw_user_meta_data ->> 'nombre', ''), split_part(new.email, '@', 1), 'Usuario')), 80),
    coalesce(new.email, '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'usuarios_nombre_largo') then
    alter table public.usuarios
      add constraint usuarios_nombre_largo check (length(trim(nombre)) between 1 and 80) not valid;
  end if;
end $$;

revoke all on table public.usuarios from anon, authenticated;
grant select (id, nombre, foto_perfil) on table public.usuarios to authenticated;
grant update (nombre, foto_perfil) on table public.usuarios to authenticated;

drop policy if exists "marketbook_usuarios_propio_select" on public.usuarios;
drop policy if exists "marketbook_usuarios_select_autenticados" on public.usuarios;
create policy "marketbook_usuarios_select_autenticados"
  on public.usuarios for select to authenticated
  using (true);

drop policy if exists "marketbook_usuarios_update_propio" on public.usuarios;
create policy "marketbook_usuarios_update_propio"
  on public.usuarios for update to authenticated
  using (id = (select auth.uid()))
  with check (id = (select auth.uid()));

-- ----------------------------------------------------------------------------
-- 2. PUBLICACIONES: un libro vendido ya no se puede editar, reactivar ni borrar,
--    y el dueño no puede marcarlo como "vendida" a mano (solo lo hace la compra).
-- ----------------------------------------------------------------------------
drop policy if exists "marketbook_publicaciones_update" on public.publicaciones;
create policy "marketbook_publicaciones_update"
  on public.publicaciones for update to authenticated
  using (vendedor_id = (select auth.uid()) and estado_publicacion <> 'vendida')
  with check (vendedor_id = (select auth.uid()) and estado_publicacion in ('activa', 'retirada'));

drop policy if exists "marketbook_publicaciones_delete" on public.publicaciones;
create policy "marketbook_publicaciones_delete"
  on public.publicaciones for delete to authenticated
  using (vendedor_id = (select auth.uid()) and estado_publicacion <> 'vendida');

-- ----------------------------------------------------------------------------
-- 3. PEDIDOS Y DETALLE. El detalle guarda una COPIA del título, autor y precio
--    para que el historial no cambie si el libro se edita o desaparece.
-- ----------------------------------------------------------------------------
create table if not exists public.pedidos (
  id bigint generated by default as identity primary key,
  comprador_id uuid not null references public.usuarios(id) on delete cascade,
  total numeric(10, 2) not null check (total > 0),
  direccion_envio text not null check (length(trim(direccion_envio)) between 5 and 250),
  metodo_pago text not null default 'simulado'
    check (metodo_pago in ('simulado', 'tarjeta', 'yape', 'contra_entrega')),
  estado text not null default 'pagado'
    check (estado in ('pagado', 'enviado', 'entregado', 'cancelado')),
  fecha timestamptz not null default now()
);

create table if not exists public.detalle_pedido (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null references public.pedidos(id) on delete cascade,
  publicacion_id bigint references public.publicaciones(id) on delete set null,
  vendedor_id uuid references public.usuarios(id) on delete set null,
  titulo text not null,
  autor text not null,
  precio numeric(10, 2) not null check (precio > 0)
);

create index if not exists pedidos_comprador_fecha_idx on public.pedidos(comprador_id, fecha desc);
create index if not exists detalle_pedido_pedido_idx on public.detalle_pedido(pedido_id);
create index if not exists detalle_pedido_vendedor_idx on public.detalle_pedido(vendedor_id);
-- Cada ejemplar físico se puede vender una sola vez.
create unique index if not exists detalle_pedido_publicacion_unica
  on public.detalle_pedido(publicacion_id) where publicacion_id is not null;

alter table public.pedidos enable row level security;
alter table public.detalle_pedido enable row level security;

-- Nadie escribe directamente: pedidos y detalle se crean SOLO con crear_pedido().
revoke all on table public.pedidos, public.detalle_pedido from anon, authenticated;
grant select on table public.pedidos, public.detalle_pedido to authenticated;

drop policy if exists "marketbook_pedidos_select_comprador" on public.pedidos;
create policy "marketbook_pedidos_select_comprador"
  on public.pedidos for select to authenticated
  using (comprador_id = (select auth.uid()));

drop policy if exists "marketbook_detalle_select_comprador" on public.detalle_pedido;
create policy "marketbook_detalle_select_comprador"
  on public.detalle_pedido for select to authenticated
  using (exists (
    select 1 from public.pedidos p
    where p.id = detalle_pedido.pedido_id and p.comprador_id = (select auth.uid())
  ));

-- ----------------------------------------------------------------------------
-- 4. crear_pedido(): la COMPRA. Todo ocurre en una sola transacción:
--    valida, bloquea los libros, crea el pedido, copia el detalle y los marca
--    como vendidos. Si algo falla, no se guarda nada.
-- ----------------------------------------------------------------------------
create or replace function public.crear_pedido(
  p_publicaciones bigint[],
  p_direccion text,
  p_metodo_pago text default 'simulado'
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := (select auth.uid());
  v_ids bigint[];
  v_validos int;
  v_total numeric(10, 2);
  v_pedido_id bigint;
  v_no_disponibles text;
  v_resultado jsonb;
begin
  if v_uid is null then
    raise exception 'Debes iniciar sesión para comprar.';
  end if;
  if p_publicaciones is null or coalesce(array_length(p_publicaciones, 1), 0) = 0 then
    raise exception 'Tu carrito está vacío.';
  end if;
  if p_direccion is null or length(trim(p_direccion)) < 5 then
    raise exception 'Ingresa una dirección de envío válida (mínimo 5 caracteres).';
  end if;
  if length(trim(p_direccion)) > 250 then
    raise exception 'La dirección es demasiado larga.';
  end if;
  if coalesce(p_metodo_pago, '') not in ('simulado', 'tarjeta', 'yape', 'contra_entrega') then
    raise exception 'Método de pago no válido.';
  end if;

  select array_agg(distinct x order by x) into v_ids from unnest(p_publicaciones) as x;
  if array_length(v_ids, 1) > 20 then
    raise exception 'Máximo 20 libros por pedido.';
  end if;

  -- Bloqueo en orden fijo: si dos personas compran el mismo libro a la vez,
  -- la segunda espera y luego ve que ya no está disponible.
  perform 1 from public.publicaciones where id = any(v_ids) order by id for update;

  select count(*), coalesce(sum(precio), 0)
    into v_validos, v_total
    from public.publicaciones
   where id = any(v_ids) and estado_publicacion = 'activa' and vendedor_id <> v_uid;

  if v_validos <> array_length(v_ids, 1) then
    if exists (select 1 from public.publicaciones where id = any(v_ids) and vendedor_id = v_uid) then
      raise exception 'No puedes comprar tu propio libro. Quítalo del carrito.';
    end if;
    select string_agg('"' || titulo || '"', ', ') into v_no_disponibles
      from public.publicaciones where id = any(v_ids) and estado_publicacion <> 'activa';
    if v_no_disponibles is not null then
      raise exception 'Ya no está disponible: %. Quítalo del carrito.', v_no_disponibles;
    end if;
    raise exception 'Alguno de los libros ya no existe. Actualiza tu carrito.';
  end if;

  insert into public.pedidos (comprador_id, total, direccion_envio, metodo_pago)
  values (v_uid, v_total, trim(p_direccion), p_metodo_pago)
  returning id into v_pedido_id;

  insert into public.detalle_pedido (pedido_id, publicacion_id, vendedor_id, titulo, autor, precio)
  select v_pedido_id, id, vendedor_id, titulo, autor, precio
    from public.publicaciones where id = any(v_ids);

  update public.publicaciones set estado_publicacion = 'vendida' where id = any(v_ids);

  select jsonb_build_object(
           'id', p.id, 'fecha', p.fecha, 'total', p.total, 'estado', p.estado,
           'direccion_envio', p.direccion_envio, 'metodo_pago', p.metodo_pago,
           'items', (
             select coalesce(jsonb_agg(jsonb_build_object(
                      'publicacion_id', d.publicacion_id, 'titulo', d.titulo,
                      'autor', d.autor, 'precio', d.precio, 'vendedor_id', d.vendedor_id
                    ) order by d.id), '[]'::jsonb)
               from public.detalle_pedido d where d.pedido_id = p.id)
         )
    into v_resultado
    from public.pedidos p where p.id = v_pedido_id;

  return v_resultado;
end;
$$;

-- ----------------------------------------------------------------------------
-- 5. mis_ventas(): historial de lo que YO vendí (con nombre y dirección del
--    comprador, necesarios para despachar el pedido).
-- ----------------------------------------------------------------------------
create or replace function public.mis_ventas()
returns table (
  id bigint, pedido_id bigint, fecha timestamptz, titulo text, autor text,
  precio numeric, estado text, comprador_nombre text, direccion_envio text
)
language sql
stable
security definer
set search_path = ''
as $$
  select d.id, d.pedido_id, p.fecha, d.titulo, d.autor, d.precio, p.estado,
         u.nombre, p.direccion_envio
    from public.detalle_pedido d
    join public.pedidos p on p.id = d.pedido_id
    left join public.usuarios u on u.id = p.comprador_id
   where d.vendedor_id = (select auth.uid())
   order by p.fecha desc, d.id desc;
$$;

-- Solo usuarios con sesión pueden ejecutar las funciones (no visitantes).
revoke all on function public.crear_pedido(bigint[], text, text) from public, anon;
revoke all on function public.mis_ventas() from public, anon;
grant execute on function public.crear_pedido(bigint[], text, text) to authenticated;
grant execute on function public.mis_ventas() to authenticated;

-- Pedir a la API REST que reconozca las tablas y funciones nuevas.
notify pgrst, 'reload schema';
